export const AllProps = {
	altLabels: false,
	bgColor: undefined,
	border: undefined,
	canReview: true,
	color: 'primary',
	density: 'default' as const,
	disabled: false,
	editable: false,
	hideDetails: false,
	nextText: '$vuetify.stepper.next',
	pages: () => [],
	prevText: '$vuetify.stepper.prev',
	title: undefined,
	transition: 'fade-transition',
	variant: undefined,
	width: '100%',
};
